### PR TITLE
fix issue #6

### PR DESCRIPTION
**Pull request by antonum**
This PR addresses #6 

Changes:
- Add ipywidgets, bump up the llama_index version to 0.8.26 in `pip install`
- Adjust `CHUNK_OVERLAP` to match the latest API (float between 0 and 1)
- Set `REDIS_ADDRESS=redis` to match docker-compose. (previously - localhost)

### CODE REVIEW

**Comment by antonum** [comment]
Added fix for issue #5 

- OPENAI_API_VERSION declared in .env file

**Comment by Spartee** [comment]
@antonum did you test this on Azure Openai or OpenAI or both?

**Comment by antonum** [comment]
Tested on both. OPENAI_API_VERSION requirement is specific to Azure and should be omitted for OpenAI. As far as I can see API specs deviated enough, so there is no single API version number that one can use for both.

I guess we can add clarification in `.env.template` like:
```
# use OPENAI_API_VERSION only when working with Azure OpenAI
```

Here is the version info from Azure: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference

OpenAI doesn't even explicitly document OPENAI_API_VERSION, but if supplied  - responds with the following error:
 'Unsupported OpenAI-Version header provided: 2023-05-15. (HINT: you can provide any of the following supported versions: 2020-10-01, 2020-11-07. Alternatively, you can simply omit this header to use the default version associated with your account.)'

**Review by Spartee — APPROVED** [review]
LGTM thanks for jumping on this Anton.

**Pull request merged**
